- name: disable SELinux
  selinux:
    state: disabled

- name: copy vhosts.conf
  template:
    src: templates/vhosts.conf.j2
    dest: /etc/httpd/conf.d/vhosts.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - activate and restart httpd

- name: copy php.ini
  template:
    src: templates/php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 0644
  notify:
    - activate and restart httpd

- name: create database "oneline_bbs"
  mysql_db: name=oneline_bbs state=present encoding=utf8

- name: recreate table "post" for database "oneline_bbs"
  mysql_db: name=oneline_bbs state=import target=/vagrant/sql/oneline_bbs.sql
