- hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    #### SELinux
    - name: disable SELinux
      selinux:
        state: disabled
    #### MySQL
    - name: remove mariadb libraries
      yum:
        name: mariadb-libs
        state: absent
    - name: add mysql repository
      yum:
        name: http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm
    - name: install mysql 5.7 community server
      yum:
        name: "{{item}}"
        state: present
      with_items:
        - mysql-community-server
        - MySQL-python
    - name: activate mysql
      service:
        name: mysqld
        enabled: yes
        state: restarted
    - name: get initial password for root user
      shell: grep 'temporary password is generated' /var/log/mysqld.log | awk '{print $11}'
      register: mysql_default_root_password
    - name: change password
      shell: mysqladmin -u root -p'{{mysql_default_root_password.stdout}}' password 'Passw0rd!'
    - name: copy .my.cnf for root user
      template:
        src: templates/mysql/.my.cnf.j2
        dest: /root/.my.cnf
        owner: root
        group: root
        mode: 0600
    #### PHP
    - name: install PHP
      yum:
        name: "{{item}}"
      with_items:
        - php
        - php-pear
        - php-devel
        - php-mbstring
        - php-mysql
        - php-pdo
        - php-xml
    #### Apache settings
    - name: copy vhosts.conf
      template:
        src: templates/apache/vhosts.conf.j2
        dest: /etc/httpd/conf.d/vhosts.conf
        owner: root
        group: root
        mode: 0644
    - name: activate httpd and restart
      service:
        name: httpd
        enabled: yes
        state: restarted
    #### common tools
    - name: install common tools
      yum:
        name: "{{item}}"
      with_items:
        - vim
